# Generated by Django 2.2.7 on 2019-12-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191226_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
    ]
