# Generated by Django 3.0.1 on 2019-12-27 18:49

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191226_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='../media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True, verbose_name='الموقع'),
        ),
    ]
