# Generated by Django 2.2.7 on 2019-12-29 19:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='المهنة')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='وصف المهنة')),
                ('thumbnail', models.ImageField(blank=True, upload_to='./media/service_thumbnails', verbose_name='صورة توضيحية')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./media/profile_pics', verbose_name='صورة شخصية'),
        ),
    ]
