# Generated by Django 2.2.8 on 2020-01-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200103_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='number_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
