# Generated by Django 2.2.8 on 2020-01-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200103_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_votes',
            field=models.IntegerField(default=0, verbose_name='عدد الأصوات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='number_votes',
            field=models.IntegerField(default=0, verbose_name='عدد الأصوات'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rate',
            field=models.FloatField(default=0.0, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Service', verbose_name='المهنة'),
        ),
    ]
