# Generated by Django 2.2.8 on 2020-01-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200103_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف المهنة'),
        ),
    ]
